# -*- coding: utf-8 -*-
"""Ejercicio 2 AdM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1en0jZqI4nYmxEGDFPfnHU1NWIuc3AdU1
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

mediaA = 50;
mediaB = 30;
muestras = 50;
desvioA = 5.0;
desvioB = 1.5;

np.random.seed(1);
A = pd.DataFrame(np.random.normal(loc= mediaA, scale=desvioA, size=muestras), columns=['A']);
print(A);
B = pd.DataFrame(np.random.normal(loc=mediaB, scale=desvioB, size=muestras), columns=['B']));
print(B);
A;
B;

sns.pairplot(A, diag_kind="kde");
sns.pairplot(B, diag_kind="kde");
Grafico = pd.concat([A,B],ignore_index= True);
sns.pairplot(Grafico,diag_kind="kde");

Grafico[0]

valor_de_clasificacion_Naranjas = mediaA - 3*desvioA;
valor_de_clasificacion_Mandarinas = mediaB + 3*desvioB;

valor_de_clasificacion = (valor_de_clasificacion_Naranjas + valor_de_clasificacion_Mandarinas)/2

prediccion = [True if  x < valor_de_clasificacion else False for x in Grafico[0]];

es_naranja = [True if x == A. else False for x in Grafico[0]];


Verdadero_Positivo = (prediccion) & (es_naranja);